// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tarea9_10.Data;

namespace Tarea9_10.Migrations
{
    [DbContext(typeof(IglesiaDbContext))]
    partial class IglesiaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Tarea9_10.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Cant_Disc")
                        .HasColumnType("int");

                    b.Property<string>("Casado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Causas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Celular")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad_Nac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ciudad_Res")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Denominacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Disciplinado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Documento_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Empr_Negocio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoCivil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exp_Razon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Expulsado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("F_Bautismo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("F_Conversion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("F_Iglesia")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("F_Nacimiento")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Foto")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Funcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Iglesia_Actual")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Iglesia_Anterior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mini_llamado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Minis_frutos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ministerios")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("N_Estudio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("N_Hijos")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ocu_Actual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais_Nac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pais_Res")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pastor_Actual")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prof_Tele")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profesion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Respaldo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tiene_Hijos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo_Docum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Tarea9_10.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
